### ISSUE TITLE
Append list of items to existing list

### ISSUE THREAD

**Issue by zunjae** [afollestad/recyclical#10]
There's currently no function to append a list of items to an existing DataSource<T>.

The closest solution I've found is to iterate through the new list and add it to the existing one per loop. For obvious reasons this isn't efficient.

Could an .append function be added or is there any better, more efficient way of solving this?

**Comment by zunjae** [comment]
For context, I would love to have this in my own Pagination implementation

**Comment by afollestad** [comment]
Wow that's a huge oversight on my end

**Comment by afollestad** [comment]
`addAll` is available in the latest release. Plain `add` now accepts vararg items too.

**Comment by zunjae** [comment]
I'm noticing an animation difference between `.set` and `.addAll`. 

Using `.addAll` I see the first entry from the DataSource appear, then a few milliseconds later the rest appears.

I don't know much about RecyclerViews but could this be caused by your use of `notifyItemRangeInserted`

So in other words: I start with an empty list, I then use addAll to add entries to my DataSource but the animation is played twice

Using set it works fine. The animation is then played once.

**Comment by afollestad** [comment]
With `set`, there isn't any animation at all since `notifyDataSetChanged()` is used (which happens to be much less efficient that notifying of insertion)
