### ISSUE TITLE
[Feature request] Add onRecycle method for ItemDefinition

### ISSUE THREAD

**Issue by fython** [afollestad/recyclical#14]
**What module does this apply to?**

A core function in RecyclerView

**Description what you'd like to happen:**

Add a onRecycle listener setter (like `onRecycle(ViewHolder.() -> Unit)`) for `ItemDefinition` .

**Describe alternatives you've considered:**

In `RecyclerView.Adapter` we can know when our views are being recycled from `onViewRecycled(ViewHolder)` and we can interrupt some loading tasks for these recycled items. But Recyclical didn't provide this callback.

**Comment by afollestad** [comment]
In the latest release

**Comment by fython** [comment]
Nice! I think we won't lose any features in RecyclerView while using this library.
