### ISSUE TITLE
kotlin compiler error in JVM target 1.8

### ISSUE THREAD

**Issue by ShadowySpirits** [afollestad/recyclical#15]
Library Version: 0.7.2
My Device: OnePlus 5 with Android 9.0
Kotlin version: 1.3.31
Target JVM version: 1.8

When I use RecyclicalSetup.withItem, I got an error:
**Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6.**

**Comment by afollestad** [comment]
That message means your app is using SDK 1.6, you need to specify 1.8
