### ISSUE TITLE
Crash when creating a data source for multiple item classes

### ISSUE THREAD

**Issue by artnest** [afollestad/recyclical#18]
**Library Version:**

1.0.0-RC2
 
**Describe the Bug:**

An app crashes when I create a data source for multiple item classes with the constructor.

In Fragment if I do this:
```kotlin
private val dataSource = emptyDataSource()

override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
    dataSource.add(AccountsHeader, Buttons)

    recyclerView.setup {
        withDataSource(dataSource)
        ...
    }
}
```
it works, but if I do it like this:
```kotlin
private val dataSource = dataSourceOf(AccountsHeader, Buttons)

override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
    dataSource.add(AccountsHeader, Buttons)

    recyclerView.setup {
        withDataSource(dataSource)
        ...
    }
}
```
app crashes.

AccountsHeader and Buttons are just objects:
```kotlin
object AccountsHeader
object Buttons
```
I have also tried using empty classes, classes with a single useless property and data classes.

**Expected Behavior:**

An app didn't crash and showed me RecyclerView.

**Comment by afollestad** [comment]
Should be fixed in the latest release
