### ISSUE TITLE
DebouncingOnClickListener

### ISSUE THREAD

**Issue by zunjae** [afollestad/recyclical#19]
**What module does this apply to?**

Core

**Description what you'd like to happen:**

Clicking a view twice in a short span will call onClick twice (which makes sense, but isn't UX friendly). Using a Debouncing OnClickListener we can mitigate this issue

At first I was hesitant whether or not this should be done on application layer, however after seeing how Jake Wharton implements it in ButterKnife I'm convinced it doesn't have to. Check his code here: https://github.com/JakeWharton/butterknife/blob/master/butterknife-runtime/src/main/java/butterknife/internal/DebouncingOnClickListener.java

Read here why to use DebouncingOnClickListener: https://stackoverflow.com/questions/33191158/why-butterknife-uses-a-debouncingonclicklistener-for-onclick-methods

**Describe alternatives you've considered:**

Preventing an action from being performed twice can be done in various way in an application. For example, when launching an activity you can change the launchMode to SingleTop. Another option is to use a boolean flag which will determine whether or not a button is enabled based on an interval. While this is possible, I have no plans on doing this on _every_ view. It feels like I'm throwing too much UI logic in my activity even tho it can be encapsulated in this library.

I'm not sure how much effort is required to implement DebouncingOnClickListener natively in recyclical, however I would appreciate if you could do so. The provided link from ButterKnife contains the code required to make it.

**Comment by afollestad** [comment]
We use debounced click listeners everywhere at Square as well.

Will implement.

**Comment by Polyterative** [comment]
I usually workaround this by making the listener emit an event through RxJava/Kotlin and applying debounce function on this emitted stream
