### ISSUE TITLE
cant find recyclerView.setup{}

### ISSUE THREAD

**Issue by gzodx** [afollestad/recyclical#22]
**Library Version:**

0.5.0
 
 
**Describe the Bug:**

i imported your project yet cant find find recyclerView.setup{}
or any related

**Comment by afollestad** [comment]
Are you using Kotlin? Make sure you're using Kotlin 1.3.31 or above

**Comment by gzodx** [comment]
Yh sure the latest version

**Comment by gzodx** [comment]
ext.kotlin_version = '1.3.41'
this is the version i am using

**Comment by gzodx** [comment]
![bug](https://user-images.githubusercontent.com/31355965/62827887-72f63900-bb8e-11e9-835d-da86f80b74e0.png)
take a loook
`

**Comment by afollestad** [comment]
This has nothing to do with the library. You're not calling `setup` on a declared `RecyclerView` variable.

**Comment by gzodx** [comment]
Thanks wasnt just thinking right
