### ISSUE TITLE
Add ability to set Layout Animation via DSL

### ISSUE THREAD

**Issue by ed-george** [afollestad/recyclical#24]
**What module does this apply to?**

Core

**Description what you'd like to happen:**

It would be great to add a `withLayoutAnimation(@AnimRes animRes: Int)` method to the DSL to allow an easy `RecyclerView.setLayoutAnimation` alternative.

**Describe alternatives you've considered:**

You can add layout animations to the RecyclerView via `setLayoutAnimation` but there's a little bit of boilerplate required to do this. 

Alternatively, it can be set via layout XML using`android:layoutAnimation`

**Comment by seanghay** [comment]
You could write your own extension function to `RecyclicalSetup` class.

```kotlin
import android.view.animation.AnimationUtils
import android.view.animation.LayoutAnimationController
import androidx.annotation.AnimRes
import com.afollestad.recyclical.RecyclicalSetup

fun RecyclicalSetup.withLayoutAnimation(@AnimRes animRes: Int, delay: Float = 0.5f) {
    val anim = AnimationUtils.loadAnimation(recyclerView.context, animRes)
    anim.duration = 250L
    val controller = LayoutAnimationController(anim, delay)
    recyclerView.layoutAnimation = controller
}
```

## Usage
In your RecyclerView setup
```kotlin
recyclerView.setup {
     withLayoutAnimation(R.anim.my_anim)
     ...
}
```

**Comment by ed-george** [comment]
Thanks @seanghay, that is pretty much exactly what I have ended up doing - I should have added that to this discussion. Would there be any value in your opinion in adding something like this to the library?

**Comment by seanghay** [comment]
> Thanks @seanghay, that is pretty much exactly what I have ended up doing - I should have added that to this discussion. Would there be any value in your opinion in adding something like this to the library?

Of course, it will be useful!
