### ISSUE TITLE
Provide an easier way to observe clicks on item child views

### ISSUE THREAD

**Issue by alexxxdev** [afollestad/recyclical#3]
example: we have several buttons in the list item.

**Comment by afollestad** [comment]
You'd set a click listener to the view from `onBind`

**Comment by alexxxdev** [comment]
I think that this is not a good idea, because it is better for listeners to install in createViewHolder, and not in bindViewHolder

**Comment by afollestad** [comment]
True, you answered your own question

**Comment by afollestad** [comment]
This should work much better for you: https://github.com/afollestad/recyclical#child-view-clicks
