### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by ZaydelEduard** [afollestad/recyclical#4]
Hey, thx for your library, very useful.
But, what about new features? 
Will be great to implement:
- footer / header;
- auto load more;
- drag & drop; 
- swipeable item; 
- expandable item;
- item grouping by section;
- etc.

**Comment by afollestad** [comment]
Individual feature requests should be separate GitHub issues.

**Comment by afollestad** [comment]
I've created separate issues for some, but do not plan to implement drag & drop or expandable items. The others are possibilities.
